# Generated by Django 4.2.28 on 2026-02-13 04:58

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded chest X-ray image.', upload_to=api.models.prediction_image_upload_path)),
                ('image_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the image bytes for cache lookups.', max_length=64, unique=True)),
                ('predicted_class', models.CharField(choices=[('COVID-19', 'COVID-19'), ('Tuberculosis', 'Tuberculosis'), ('Bacterial Pneumonia', 'Bacterial Pneumonia'), ('Viral Pneumonia', 'Viral Pneumonia'), ('Normal', 'Normal'), ('Unknown', 'Unknown')], default='Unknown', max_length=64)),
                ('confidence_score', models.FloatField(help_text='Model confidence in the prediction (0-1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('urgency_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM_HIGH', 'Medium-High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=32)),
                ('urgency_color', models.CharField(help_text='Tailwind-compatible color name for frontend badges.', max_length=16)),
                ('urgency_icon', models.CharField(help_text='Unicode icon representing urgency.', max_length=8)),
                ('immediate_actions', models.JSONField(default=list, help_text='Immediate actions to take for this disease.')),
                ('medical_recommendations', models.JSONField(default=list, help_text='Medical recommendations and interventions.')),
                ('lifestyle_recommendations', models.JSONField(default=list, help_text='Lifestyle changes to support recovery.')),
                ('follow_up', models.TextField(help_text='Follow-up guidance and typical timelines.')),
                ('disclaimer', models.TextField(default='This is an AI-assisted screening tool. Not a medical diagnosis. Consult a healthcare provider.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_time_ms', models.FloatField(help_text='End-to-end processing time in milliseconds.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cached_result', models.BooleanField(default=False, help_text='Whether this prediction was served from cache.')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['image_hash'], name='idx_image_hash'), models.Index(fields=['predicted_class'], name='idx_predicted_class'), models.Index(fields=['created_at'], name='idx_created_at')],
            },
        ),
    ]
