from __future__ import annotations

import logging
import os
import threading
from pathlib import Path
from time import perf_counter
from typing import Tuple

import numpy as np
import tensorflow as tf
from PIL import Image

from .model import IMAGE_SIZE, create_model, compile_model


logger = logging.getLogger(__name__)

_model: tf.keras.Model | None = None
_model_lock = threading.Lock()

NUM_CLASSES = 17 


def _load_model() -> tf.keras.Model:
    """Load the trained model from disk.

    Loads the full .keras model generated by Kaggle.
    """
    global _model
    
    default_path = str(
        Path(__file__).resolve().parent / "saved_models" / "model.keras"
    )
    model_path = os.getenv("MODEL_PATH", default_path)
    logger.info("Loading ML model from %s", model_path)
    start = perf_counter()

    # Load full architecture and weights natively (no custom scope needed for .keras!)
    _model = tf.keras.models.load_model(model_path, compile=False, safe_mode=False)

    elapsed = (perf_counter() - start) * 1000
    logger.info("Model loaded in %.2f ms", elapsed)
    return _model


def get_model() -> tf.keras.Model:
    """Return the global model instance, loading it once with double-checked locking."""
    global _model
    if _model is None:
        with _model_lock:
            if _model is None:
                _load_model()
    assert _model is not None
    return _model


def reload_model() -> None:
    """Force-reload the model from disk (e.g. after retraining).

    Thread-safe: acquires the model lock before clearing the cached instance.
    The next call to ``get_model()`` will load the updated weights.
    """
    global _model
    with _model_lock:
        _model = None
    logger.info("Model cache cleared — next prediction will load fresh weights.")


def preprocess_image(image_path: str) -> np.ndarray:
    """Load and preprocess an image file for DenseNet121 prediction.
    """
    img = Image.open(image_path).convert("RGB")
    img = img.resize(IMAGE_SIZE, Image.LANCZOS)
    arr = np.asarray(img, dtype=np.float32) 
    # The Keras model was trained with ImageDataGenerator(rescale=1./255)
    # The architecture natively handles DenseNet preprocessing by doing (x * 255)
    # before calling the internal preprocess_input. Therefore, we just need [0, 1].
    arr = np.expand_dims(arr, axis=0)
    arr = arr / 255.0
    return arr


def predict_image(image_path: str, class_names: list[str]) -> Tuple[str, float, float]:
    """Run inference on an image and return (predicted_class, confidence, time_ms)."""
    model = get_model()
    inputs = preprocess_image(image_path)

    start = perf_counter()
    preds = model.predict(inputs, verbose=0)  # type: ignore[no-untyped-call]
    elapsed_ms = (perf_counter() - start) * 1000.0

    probs = preds[0]
    idx = int(np.argmax(probs))
    confidence = float(probs[idx])
    predicted_class = class_names[idx] if idx < len(class_names) else "Unknown"

    logger.info(
        "Prediction: %s (%.2f%%) in %.2f ms",
        predicted_class,
        confidence * 100.0,
        elapsed_ms,
    )
    return predicted_class, confidence, elapsed_ms

